/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    // maven {
    //     url = uri("https://repo.dmulloy2.net/repository/public/")
    // }

    // maven {
    //     url = uri("https://repo.maven.apache.org/maven2/")
    // }
    maven { url = uri("https://maven.pkg.github.com/tomlj/tomlj") }
}

dependencies {
    // api(libs.com.moandjiezana.toml.toml4j)
    // api(libs.org.apache.maven.plugins.maven.assembly.plugin)
    // compileOnly(libs.io.papermc.paper.paper.api)
    // implementation("com.moandjiezana.toml:toml4j:0.7.2")
    implementation("org.tomlj:tomlj:1.1.1")
    implementation("com.google.code.gson:gson:2.11.0")
    // compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    compileOnly("io.papermc.paper:paper-api:1.21.10-R0.1-SNAPSHOT")
}

group = "com.kingtheguy.magic"
version = "1.3"
description = "portalis"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}
