/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    // maven {
    //     url = uri("https://repo.dmulloy2.net/repository/public/")
    // }

    // maven {
    //     url = uri("https://repo.maven.apache.org/maven2/")
    // }
}

dependencies {
    // api(libs.com.moandjiezana.toml.toml4j)
    // api(libs.org.apache.maven.plugins.maven.assembly.plugin)
    // compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    implementation("com.moandjiezana.toml:toml4j:0.7.2")
    implementation("com.google.code.gson:gson:2.11.0")
}

group = "com.kingtheguy.magic"
version = "1.0"
description = "portalis"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}
