name: portalis
version: 1.2
author: KingTheGuy
main: com.kingtheguy.magic
api-version: 1.20
commands:
  givebook:
    description: give book
    # usage: /<command>
  giveinfusedpaper:
    description: give infused paper
    # usage: /<command>
  setselectioncolor:
    description: set the dial menu selection color
    # usage: /<command>
  giverippedpage:
    description: give ripped page
    # usage: /<command>
